if(EXISTS "/tmp/bustub/_build/test/buffer_pool_manager_test[1]_tests.cmake")
  include("/tmp/bustub/_build/test/buffer_pool_manager_test[1]_tests.cmake")
else()
  add_test(buffer_pool_manager_test_NOT_BUILT buffer_pool_manager_test_NOT_BUILT)
endif()
