# CMake generated Testfile for 
# Source directory: /tmp/bustub/test
# Build directory: /tmp/bustub/_build/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("/tmp/bustub/_build/test/crash_test[1]_include.cmake")
include("/tmp/bustub/_build/test/binder_test[1]_include.cmake")
include("/tmp/bustub/_build/test/buffer_pool_manager_test[1]_include.cmake")
include("/tmp/bustub/_build/test/clock_replacer_test[1]_include.cmake")
include("/tmp/bustub/_build/test/lru_k_replacer_test[1]_include.cmake")
include("/tmp/bustub/_build/test/lru_replacer_test[1]_include.cmake")
include("/tmp/bustub/_build/test/rwlatch_test[1]_include.cmake")
include("/tmp/bustub/_build/test/extendible_htable_concurrent_test[1]_include.cmake")
include("/tmp/bustub/_build/test/extendible_htable_test[1]_include.cmake")
include("/tmp/bustub/_build/test/hash_table_page_test[1]_include.cmake")
include("/tmp/bustub/_build/test/hash_table_test[1]_include.cmake")
include("/tmp/bustub/_build/test/hyperloglog_test[1]_include.cmake")
include("/tmp/bustub/_build/test/orset_test[1]_include.cmake")
include("/tmp/bustub/_build/test/skiplist_test[1]_include.cmake")
include("/tmp/bustub/_build/test/trie_debug_test[1]_include.cmake")
include("/tmp/bustub/_build/test/trie_noncopy_test[1]_include.cmake")
include("/tmp/bustub/_build/test/trie_store_noncopy_test[1]_include.cmake")
include("/tmp/bustub/_build/test/trie_store_test[1]_include.cmake")
include("/tmp/bustub/_build/test/trie_test[1]_include.cmake")
include("/tmp/bustub/_build/test/b_plus_tree_concurrent_test[1]_include.cmake")
include("/tmp/bustub/_build/test/b_plus_tree_contention_test[1]_include.cmake")
include("/tmp/bustub/_build/test/b_plus_tree_delete_test[1]_include.cmake")
include("/tmp/bustub/_build/test/b_plus_tree_insert_test[1]_include.cmake")
include("/tmp/bustub/_build/test/b_plus_tree_sequential_scale_test[1]_include.cmake")
include("/tmp/bustub/_build/test/disk_manager_test[1]_include.cmake")
include("/tmp/bustub/_build/test/disk_scheduler_test[1]_include.cmake")
include("/tmp/bustub/_build/test/extendible_htable_page_test[1]_include.cmake")
include("/tmp/bustub/_build/test/page_guard_test[1]_include.cmake")
include("/tmp/bustub/_build/test/tmp_tuple_page_test[1]_include.cmake")
include("/tmp/bustub/_build/test/tuple_test[1]_include.cmake")
include("/tmp/bustub/_build/test/txn_abort_serializable_test[1]_include.cmake")
include("/tmp/bustub/_build/test/txn_executor_test[1]_include.cmake")
include("/tmp/bustub/_build/test/txn_index_concurrent_test[1]_include.cmake")
include("/tmp/bustub/_build/test/txn_index_test[1]_include.cmake")
include("/tmp/bustub/_build/test/txn_scan_test[1]_include.cmake")
include("/tmp/bustub/_build/test/txn_timestamp_test[1]_include.cmake")
include("/tmp/bustub/_build/test/type_test[1]_include.cmake")
add_test(SQLLogicTest.p0.01-lower-upper "/tmp/bustub/_build/bin/bustub-sqllogictest" "/tmp/bustub/test/sql/p0.01-lower-upper.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p0.01-lower-upper PROPERTIES  _BACKTRACE_TRIPLES "/tmp/bustub/test/CMakeLists.txt;90;add_test;/tmp/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p0.02-function-error "/tmp/bustub/_build/bin/bustub-sqllogictest" "/tmp/bustub/test/sql/p0.02-function-error.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p0.02-function-error PROPERTIES  _BACKTRACE_TRIPLES "/tmp/bustub/test/CMakeLists.txt;90;add_test;/tmp/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p0.03-string-scan "/tmp/bustub/_build/bin/bustub-sqllogictest" "/tmp/bustub/test/sql/p0.03-string-scan.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p0.03-string-scan PROPERTIES  _BACKTRACE_TRIPLES "/tmp/bustub/test/CMakeLists.txt;90;add_test;/tmp/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.01-seqscan "/tmp/bustub/_build/bin/bustub-sqllogictest" "/tmp/bustub/test/sql/p3.01-seqscan.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.01-seqscan PROPERTIES  _BACKTRACE_TRIPLES "/tmp/bustub/test/CMakeLists.txt;90;add_test;/tmp/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.02-insert "/tmp/bustub/_build/bin/bustub-sqllogictest" "/tmp/bustub/test/sql/p3.02-insert.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.02-insert PROPERTIES  _BACKTRACE_TRIPLES "/tmp/bustub/test/CMakeLists.txt;90;add_test;/tmp/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.03-update "/tmp/bustub/_build/bin/bustub-sqllogictest" "/tmp/bustub/test/sql/p3.03-update.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.03-update PROPERTIES  _BACKTRACE_TRIPLES "/tmp/bustub/test/CMakeLists.txt;90;add_test;/tmp/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.04-delete "/tmp/bustub/_build/bin/bustub-sqllogictest" "/tmp/bustub/test/sql/p3.04-delete.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.04-delete PROPERTIES  _BACKTRACE_TRIPLES "/tmp/bustub/test/CMakeLists.txt;90;add_test;/tmp/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.05-index-scan-btree "/tmp/bustub/_build/bin/bustub-sqllogictest" "/tmp/bustub/test/sql/p3.05-index-scan-btree.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.05-index-scan-btree PROPERTIES  _BACKTRACE_TRIPLES "/tmp/bustub/test/CMakeLists.txt;90;add_test;/tmp/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.06-empty-table "/tmp/bustub/_build/bin/bustub-sqllogictest" "/tmp/bustub/test/sql/p3.06-empty-table.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.06-empty-table PROPERTIES  _BACKTRACE_TRIPLES "/tmp/bustub/test/CMakeLists.txt;90;add_test;/tmp/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.07-simple-agg "/tmp/bustub/_build/bin/bustub-sqllogictest" "/tmp/bustub/test/sql/p3.07-simple-agg.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.07-simple-agg PROPERTIES  _BACKTRACE_TRIPLES "/tmp/bustub/test/CMakeLists.txt;90;add_test;/tmp/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.08-group-agg-1 "/tmp/bustub/_build/bin/bustub-sqllogictest" "/tmp/bustub/test/sql/p3.08-group-agg-1.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.08-group-agg-1 PROPERTIES  _BACKTRACE_TRIPLES "/tmp/bustub/test/CMakeLists.txt;90;add_test;/tmp/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.09-group-agg-2 "/tmp/bustub/_build/bin/bustub-sqllogictest" "/tmp/bustub/test/sql/p3.09-group-agg-2.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.09-group-agg-2 PROPERTIES  _BACKTRACE_TRIPLES "/tmp/bustub/test/CMakeLists.txt;90;add_test;/tmp/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.10-simple-join "/tmp/bustub/_build/bin/bustub-sqllogictest" "/tmp/bustub/test/sql/p3.10-simple-join.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.10-simple-join PROPERTIES  _BACKTRACE_TRIPLES "/tmp/bustub/test/CMakeLists.txt;90;add_test;/tmp/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.11-multi-way-join "/tmp/bustub/_build/bin/bustub-sqllogictest" "/tmp/bustub/test/sql/p3.11-multi-way-join.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.11-multi-way-join PROPERTIES  _BACKTRACE_TRIPLES "/tmp/bustub/test/CMakeLists.txt;90;add_test;/tmp/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.12-repeat-execute "/tmp/bustub/_build/bin/bustub-sqllogictest" "/tmp/bustub/test/sql/p3.12-repeat-execute.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.12-repeat-execute PROPERTIES  _BACKTRACE_TRIPLES "/tmp/bustub/test/CMakeLists.txt;90;add_test;/tmp/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.13-nested-index-join "/tmp/bustub/_build/bin/bustub-sqllogictest" "/tmp/bustub/test/sql/p3.13-nested-index-join.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.13-nested-index-join PROPERTIES  _BACKTRACE_TRIPLES "/tmp/bustub/test/CMakeLists.txt;90;add_test;/tmp/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.14-hash-join "/tmp/bustub/_build/bin/bustub-sqllogictest" "/tmp/bustub/test/sql/p3.14-hash-join.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.14-hash-join PROPERTIES  _BACKTRACE_TRIPLES "/tmp/bustub/test/CMakeLists.txt;90;add_test;/tmp/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.15-multi-way-hash-join "/tmp/bustub/_build/bin/bustub-sqllogictest" "/tmp/bustub/test/sql/p3.15-multi-way-hash-join.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.15-multi-way-hash-join PROPERTIES  _BACKTRACE_TRIPLES "/tmp/bustub/test/CMakeLists.txt;90;add_test;/tmp/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.16-sort-limit "/tmp/bustub/_build/bin/bustub-sqllogictest" "/tmp/bustub/test/sql/p3.16-sort-limit.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.16-sort-limit PROPERTIES  _BACKTRACE_TRIPLES "/tmp/bustub/test/CMakeLists.txt;90;add_test;/tmp/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.17-topn "/tmp/bustub/_build/bin/bustub-sqllogictest" "/tmp/bustub/test/sql/p3.17-topn.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.17-topn PROPERTIES  _BACKTRACE_TRIPLES "/tmp/bustub/test/CMakeLists.txt;90;add_test;/tmp/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.18-integration-1 "/tmp/bustub/_build/bin/bustub-sqllogictest" "/tmp/bustub/test/sql/p3.18-integration-1.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.18-integration-1 PROPERTIES  _BACKTRACE_TRIPLES "/tmp/bustub/test/CMakeLists.txt;90;add_test;/tmp/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.19-integration-2 "/tmp/bustub/_build/bin/bustub-sqllogictest" "/tmp/bustub/test/sql/p3.19-integration-2.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.19-integration-2 PROPERTIES  _BACKTRACE_TRIPLES "/tmp/bustub/test/CMakeLists.txt;90;add_test;/tmp/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.20-window-function "/tmp/bustub/_build/bin/bustub-sqllogictest" "/tmp/bustub/test/sql/p3.20-window-function.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.20-window-function PROPERTIES  _BACKTRACE_TRIPLES "/tmp/bustub/test/CMakeLists.txt;90;add_test;/tmp/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.leaderboard-q1 "/tmp/bustub/_build/bin/bustub-sqllogictest" "/tmp/bustub/test/sql/p3.leaderboard-q1.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.leaderboard-q1 PROPERTIES  _BACKTRACE_TRIPLES "/tmp/bustub/test/CMakeLists.txt;90;add_test;/tmp/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.leaderboard-q2 "/tmp/bustub/_build/bin/bustub-sqllogictest" "/tmp/bustub/test/sql/p3.leaderboard-q2.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.leaderboard-q2 PROPERTIES  _BACKTRACE_TRIPLES "/tmp/bustub/test/CMakeLists.txt;90;add_test;/tmp/bustub/test/CMakeLists.txt;0;")
add_test(SQLLogicTest.p3.leaderboard-q3 "/tmp/bustub/_build/bin/bustub-sqllogictest" "/tmp/bustub/test/sql/p3.leaderboard-q3.slt" "--verbose" "-d" "--in-memory")
set_tests_properties(SQLLogicTest.p3.leaderboard-q3 PROPERTIES  _BACKTRACE_TRIPLES "/tmp/bustub/test/CMakeLists.txt;90;add_test;/tmp/bustub/test/CMakeLists.txt;0;")
