if(EXISTS "/tmp/bustub/_build/test/disk_manager_test[1]_tests.cmake")
  include("/tmp/bustub/_build/test/disk_manager_test[1]_tests.cmake")
else()
  add_test(disk_manager_test_NOT_BUILT disk_manager_test_NOT_BUILT)
endif()
