if(EXISTS "/tmp/bustub/_build/test/disk_scheduler_test[1]_tests.cmake")
  include("/tmp/bustub/_build/test/disk_scheduler_test[1]_tests.cmake")
else()
  add_test(disk_scheduler_test_NOT_BUILT disk_scheduler_test_NOT_BUILT)
endif()
