if(EXISTS "/tmp/bustub/_build/test/hyperloglog_test[1]_tests.cmake")
  include("/tmp/bustub/_build/test/hyperloglog_test[1]_tests.cmake")
else()
  add_test(hyperloglog_test_NOT_BUILT hyperloglog_test_NOT_BUILT)
endif()
