if(EXISTS "/tmp/bustub/_build/test/lru_replacer_test[1]_tests.cmake")
  include("/tmp/bustub/_build/test/lru_replacer_test[1]_tests.cmake")
else()
  add_test(lru_replacer_test_NOT_BUILT lru_replacer_test_NOT_BUILT)
endif()
