if(EXISTS "/tmp/bustub/_build/test/skiplist_test[1]_tests.cmake")
  include("/tmp/bustub/_build/test/skiplist_test[1]_tests.cmake")
else()
  add_test(skiplist_test_NOT_BUILT skiplist_test_NOT_BUILT)
endif()
