if(EXISTS "/tmp/bustub/_build/test/trie_debug_test[1]_tests.cmake")
  include("/tmp/bustub/_build/test/trie_debug_test[1]_tests.cmake")
else()
  add_test(trie_debug_test_NOT_BUILT trie_debug_test_NOT_BUILT)
endif()
