if(EXISTS "/tmp/bustub/_build/test/txn_abort_serializable_test[1]_tests.cmake")
  include("/tmp/bustub/_build/test/txn_abort_serializable_test[1]_tests.cmake")
else()
  add_test(txn_abort_serializable_test_NOT_BUILT txn_abort_serializable_test_NOT_BUILT)
endif()
