 version: 2
 jobs:
   build:
     docker:
       - image: ubuntu:18.04
     steps:
       - run: apt update && apt -y install cmake
       - checkout
       - run: mkdir build
       - run: cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
       - run: cd build && make -j