 version: 2
 jobs:
   build:
     docker:
       - image: ubuntu:18.04
     steps:
       - checkout
       - run: mkdir build
       - run: cd build
       - run: cmake -DCMAKE_BUILD_TYPE=Debug ..
       - run: make