if(EXISTS "/Users/votinhluombikip/Documents/bustub-private/build_rel/test/rwlatch_test[1]_tests.cmake")
  include("/Users/votinhluombikip/Documents/bustub-private/build_rel/test/rwlatch_test[1]_tests.cmake")
else()
  add_test(rwlatch_test_NOT_BUILT rwlatch_test_NOT_BUILT)
endif()
