if(EXISTS "/Users/votinhluombikip/Documents/bustub-private/build_rel/test/txn_abort_serializable_test[1]_tests.cmake")
  include("/Users/votinhluombikip/Documents/bustub-private/build_rel/test/txn_abort_serializable_test[1]_tests.cmake")
else()
  add_test(txn_abort_serializable_test_NOT_BUILT txn_abort_serializable_test_NOT_BUILT)
endif()
